### ISSUE TITLE
Context sensitive month names in Panel

### ISSUE THREAD

**Issue by bratkartoffel** [JDatePicker/JDatePicker#44]
As suggested by @phjr with pull request #43.

DateFormatSymbols contains context sensitive form of month, we need
standalone form. This difference is not apparent in English but makes a
difference in other languages (such as Slovak in my case)

Example and explanation for russian locale:
http://stackoverflow.com/a/25329549/1164913

**Comment by bratkartoffel** [comment]
I think this one is pretty tricky, as the suggested format "LLLL" is first documented in the JDK 8 API and not mentioned in earlier versions:
- https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
- https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html

As this component should stay compatible with Java 5 I'm not sure how to get around this issue...
@juanheyns what do you think?

**Comment by phjr** [comment]
Umm, sorry about that - I didn't realize it's new in Java 8. I'll try to find some other way.

**Comment by bratkartoffel** [comment]
Looks good with Format "MMMM", tested with the following results:
Russian Locale, with Month January. Expected is a month name ending with a strange "b" ;)

JDK 5u22:
- old style: январь (OK)
- new with MMMM: январь (OK)
- new with LLLL: java.lang.IllegalArgumentException: Illegal pattern character 'L'

JDK 6u45:
- old style: январь (OK)
- new with MMMM: январь (OK)
- new with LLLL: java.lang.IllegalArgumentException: Illegal pattern character 'L'

JDK 7u71:
- old style: январь (OK)
- new with MMMM: январь (OK)
- new with LLLL: java.lang.IllegalArgumentException: Illegal pattern character 'L'

JDK 8u25:
- old style: января (wrong)
- new with MMMM: январь (OK)
- new with LLLL: январь (OK)

As you can see, everything is fine until Java 8. I'd suggest to use the SimpleDateFormat as suggested by @phjr using the "MMMM" pattern.
@juanheyns The 2 commits in pull request #43 are fine now.

**Comment by juanheyns** [comment]
Thanks for testing @bratkartoffel
