### ISSUE TITLE
DatePicker can't be enabled/disabled

### ISSUE THREAD

**Issue by wbittremieux** [JDatePicker/JDatePicker#46]
JDatePickerImpl is always enabled, ignoring the value of [setEnabled](http://docs.oracle.com/javase/7/docs/api/javax/swing/JComponent.html#setEnabled%28boolean%29). A disabled component should not respond to user input.

A straightforward solution would be to add the following setEnabled method to JDatePickerImpl:

```
public void setEnabled(boolean enabled) {
    button.setEnabled(enabled);
    formattedTextField.setEnabled(enabled);
}
```

**Comment by juanheyns** [comment]
Thanks, strange in ten years nobody ever wanted to disable it :)                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: woutbSent: Friday 30 January 2015 15:10To: JDatePicker/JDatePickerReply To: JDatePicker/JDatePickerSubject: [JDatePicker] DatePicker can't be enabled/disabled (#46)JDatePickerImpl is always enabled, ignoring the value of setEnabled(boolean). A disabled component should not respond to user input (setEnabled).

A straightforward solution would be to add the following setEnabled method to JDatePickerImpl:

public void setEnabled(boolean enabled) {
    button.setEnabled(isEnabled);
    formattedTextField.setEnabled(isEnabled);
}


—Reply to this email directly or view it on GitHub.

**Comment by bratkartoffel** [comment]
I'll open a pull request for this one, thank you @woutb

**Comment by Sammoura** [comment]
I have this simple solution:
JDatePickerImpl  myDatePicker = new .......  ;
myDatePicker.getComponent(1).setEnabled(false);

**Comment by ftomassetti** [comment]
Was the solution part of 1.3.4? It does not seem to work in 1.3.4

**Comment by ftomassetti** [comment]
Also the workaround does not seem to work

**Comment by Ferdzz** [comment]
@ftomassetti I just tried using 1.3.4 and I confirm this workaround still works
