### ISSUE TITLE
JDatePicker with Locale.German loses 01 March 2015

### ISSUE THREAD

**Issue by lewandowskil** [JDatePicker/JDatePicker#49]
Hi!

I tested this issue with JDK6 (Win 7) and the current cloned git repo (02 March 2015). When locale German is set, then the calendar starts the week with monday (as desired). But if the month starts with a sunday, then the first of the month is not selectable e.g., February 01, 2015 or March 01, 2015, because the view starts with monday March 02, 2015 . Is this a bug or is this a configuration failure?

Thanks in advanced!
Lukas

**Comment by lewandowskil** [comment]
I reproduced this with your org.jdatepicker.TestJDatePanel class.

**Comment by lewandowskil** [comment]
Is this a bug? If yes, will it be solved?

**Comment by juanheyns** [comment]
I recorded it as a bug:
https://github.com/JDatePicker/JDatePicker/issues/51

Currently working on a fix.

**Comment by juanheyns** [comment]
THis should now be fixed

**Comment by lewandowskil** [comment]
Great!! Thank your for the fix!
