### ISSUE TITLE
getMonth() form DateModel returns incorrect month number

### ISSUE THREAD

**Issue by rufusroflpunch** [JDatePicker/JDatePicker#52]
I created a component like this:

```java
JDatePicker startDate = (new JDateComponentFactory()).createJDatePicker();
mainPanel.add((Component) startDate);
```

When getting the Month form the component using `startDate.getModel().getMonth()` it seems to return a zero-indexed month. For example, it returns 0 for January, 1 for February, etc.

**Comment by bratkartoffel** [comment]
Hi,

this is not an issue in JDatePicker. This is just normal, intended behaviour of the internal Java classes as documented in the java.util.Date class:
http://docs.oracle.com/javase/7/docs/api/java/util/Date.html

Regards,
Simon

**Comment by juanheyns** [comment]
Agreed, this is the intended behaviour.
