### ISSUE TITLE
How do I construct a JDatePanel now?

### ISSUE THREAD

**Issue by apjanke** [JDatePicker/JDatePicker#53]
Since the upgrade from 1.3.2 to 1.3.4, I'm confused on how I'm supposed to be constructing `JDatePanelImpl` objects. I used to construct a `DateModel` and then call the single-argument `JDatePanelImpl(DateModel)` constructor. But that constructor is gone as of 1.3.4. And there doesn't seem to be good guidance on how to construct the `i18strings` `Properties`.

Should clients be using the `JDateComponentFactory` object instead of calling `JDatePanelImpl` constructors? Are those factory methods guaranteed to always return the `...Impl` classes so we can cast them down and use them as `JComponents` to get them in to our component tree?

Which parts of the JDatePicker library are the public interface for clients to call?

**Comment by slavkoilic** [comment]
I hope this will help you. 

UtilDateModel model = new UtilDateModel();
Properties p = new Properties();
p.put("text.today", "Today");
p.put("text.month", "Month");
p.put("text.year", "Year");
JDatePanelImpl datePanel = new JDatePanelImpl(model, p);

JDatePickerImpl datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());

**Comment by juanheyns** [comment]
1.3.4
-------
Thanks @slavkoilic this will be the correct way to do this on 1.3.4. Unfortunately the JDateComponentFactory does not have a way to construct a JDatePanelImpl by specifying the actual translated strings. 

You could of course also specify the locale to the JDateComponentFactory before constructing the JDatePanelImpl (https://github.com/JDatePicker/JDatePicker/blob/maintain-1.3.4/src/main/java/org/jdatepicker/JDateComponentFactory.java#L74)

master
---------
The approach which I am moving towards is that you can set the defaults for the components before you instantiate them. You will see on master (https://github.com/JDatePicker/JDatePicker/blob/master/src/main/java/org/jdatepicker/ComponentManager.java#L6), the ComponentManager singleton is initialised with some defaults which can be modified by calling the appropriate setter (i.e. setComponentTextDefaults).
