### ISSUE TITLE
Potential resource leak in ComponentIconDefaults.java

### ISSUE THREAD

**Issue by pableras** [JDatePicker/JDatePicker#54]
I'm compiling JDatePicker master branch with Eclipse and I'm getting this warning:

_"Potential resource leak: 'stream' may not be closed at this location"_

The warning is in _org/jdatepicker/ComponentIconDefaults.java_ at line 54.

This is easily solved closing the _stream_ object before exit:
```javascript
    ...
    BufferedImage image = ImageIO.read(stream);
    stream.close();    // <--- New line
    return new ImageIcon(image);
    ...
```
Please add this modification to master branch.

**Comment by bratkartoffel** [comment]
Hi,

in case of an IOException I'd add something like this:
```java
    ...
    try {
        BufferedImage image = ImageIO.read(stream);
    } finally {
        stream.close();    // <--- New line
    }
    return new ImageIcon(image);
    ...
```
If i find time this evening I'll create a pull request.

Simon

**Comment by pableras** [comment]
Okay, but the object _image_ must be declared outside the _try_ block:
```javascript
    ...
    BufferedImage image;
    try {
        image = ImageIO.read(stream);
    } finally {
        stream.close();    // <--- New line
    }
    return new ImageIcon(image);
    ...
```

Or better for me, leave _return_ sentence inside the _try_ block:
```javascript
    ...
    try {
        BufferedImage image = ImageIO.read(stream);
        return new ImageIcon(image);
    } finally {
        stream.close();
    }
    ...
```

Thanks a lot!
