### ISSUE TITLE
JDateComponentFactory bug in "1.3.4" release

### ISSUE THREAD

**Issue by evertonbg** [JDatePicker/JDatePicker#55]
Please: fix this bug in "JDateComponentFactory.createDateModel(Object value)"

Current (wrong) code: this line (#172) will never be reached because "java.util.Calendar" is an abstract class (https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html).
         &nbsp;&nbsp;&nbsp;      if(clazz.equals(java.util.Calendar.class)) { // Don't consider subclasses

Fixed code:
         &nbsp;&nbsp;&nbsp;     if(value instanceof java.util.Calendar) { // Consider subclasses

**Comment by juanheyns** [comment]
This has been fixed and I created a tag 1.3.4.1 which has this change. Not sure if it required that we make a maven release for this change?

**Comment by evertonbg** [comment]
Thanks! I think this fix can be postponed to the next release.
