### ISSUE TITLE
All dots instead of days

### ISSUE THREAD

**Issue by vsarunov** [JDatePicker/JDatePicker#56]
Whenever I use JDatePicker I get to select from a bunch of dots instead of month days.
![untitled](https://cloud.githubusercontent.com/assets/13823101/9295209/82f08bbe-445d-11e5-843f-80f8a1d70d49.png)

**Comment by pgoldste** [comment]
Same issue, sorta:
<img width="201" alt="screen shot 2015-08-28 at 6 45 34 pm" src="https://cloud.githubusercontent.com/assets/7990296/9558544/03331930-4db5-11e5-8a2a-66f3f609aec7.png">

**Comment by juanheyns** [comment]
I have made a commit to master (2eae18cb368893fb30195084c542558d134a9afa), which fixes a related issue. 

Unfortunately I do not have enough information about your environment to replicate the issue. If you are able, please test with the above mentioned fix to see if this resolves your issue as well.

**Comment by juanheyns** [comment]
Closing issue, please comment on this issue if the problem still persist.
