### ISSUE TITLE
setting date inside the propertyChange method triggers infinite loop

### ISSUE THREAD

**Issue by harikiran-01** [JDatePicker/JDatePicker#82]

**Comment by bratkartoffel** [comment]
I think this is expected behaviour.
The propertyChangeListener should not unconditionally modify the component as this triggers another propertyChangeEvent.

**Comment by harikiran-01** [comment]
can you suggest any work around for this? for now I am creating a propertychangelistener method inside the class, whenever the date needs to be set, I am calling a different method which turns off the listener, changes and then turns it back on.. I am just hoping there might be a better solution to achieve this
