### ISSUE TITLE
Set Min/Max Date

### ISSUE THREAD

**Issue by plastic1st** [JDatePicker/JDatePicker#83]
Hi.

I've been searching for a long time, but haven't found any explanation on how to set a minimum (or maximum) date in JDatepicker.

Sorry if the question seems trivial (I'm a newbie in Java), but is it possible to set a minimum pickable date ?
I could validate the selected date once picked, but I would rather make it impossible to select a date which is out of range...

Thanks in advance for your help.

**Comment by valentina-ferro** [comment]
Hi, it's possible set min max?
